language: java
sudo: true
jdk:
  - openjdk15

script: ./gradlew build --scan -s
before_install: chmod +x gradlew

#additions
services:
  - postgresql
addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
env:
  global:
    - PGPORT=5433
    - PGUSER=travis
#before_script:
#  - psql --version
#  - psql -U travis < test.sql
#  - psql -c 'select * from student;' -U travis
##
jobs:
  include:
    - stage: test
      script: ./gradlew test
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: simba-client-connectivity
  on: main
